# See https://github.com/dimagi/label-bot
disabled_actions:
  - triage
  - review
  - wip
  - lgtm

# Label rules
brace_expansion: true
minus_negate: false

rules:
  - labels: ['reindex/migration']
    patterns: ['**/migrations/**|corehq/pillows/mappings/**']

  - labels: ['dependencies']
    patterns: ['requirements/**|package.json|yarn.lock']

# Label management
delete_labels: false

colors:
  navy: '#0366d6'
  orange: '#eb6420'

labels:
- name: 'reindex/migration'
  color: orange
  description: 'Reindex or migration will be required during or before deploy'
- name: 'dependencies'
  color: navy
  description: 'Pull requests that update a dependency file'
